[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "73TeSkZ158uWSaaXDAFKRzdfYv5CAQFmQ63zzs15PHsd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xapski2671/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
